# Creating MLflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-deployment
  template:
    metadata:
      labels:
        app: fe-deployment
    spec:
      containers:
      - name: fe-deployment
        image: ml-streamlit 
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          value: http://mlflow-wine-default.ml-models.svc.cluster.local:8000/v2/models/classifier/infer
        ports:
        - name: http
          containerPort: 8501
          protocol: TCP
        resources:
          requests:
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8501
      protocol: TCP
      name: http
  selector:
    app: fe-deployment

